### ISSUE TITLE
I just wanna to try the demo，but I get this：IndexError: arrays used as indices must be of integer (or boolean) type

### ISSUE THREAD

**Issue by zhly0** [Eniac-Xie/PyConvNet#4]
the demo is mnist_demo.py：
    cols = x_padded[r, c, d, :]
    IndexError: arrays used as indices must be of integer (or boolean) type
in im2col.py

**Comment by Eniac-Xie** [comment]
Hi, have you ever modified the code?  I download the code and run the mnist_demo.py, it's OK.
Which version of python and numpy did you use? I test the demo with python 2.7.10 and numpy 1.9.2

**Comment by zhly0** [comment]
thanks for your reply！I think maybe the different edition of python lead to this，my python is the latest python3.5,
